version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mynet
  
  pg4admin:
    image: dpage/pgadmin4
    container_name: pg4admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    networks:
      - mynet
    depends_on:
      - postgres
  
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
        - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - mynet
  
  manager:
    image: emqx/ekuiper-manager:1.8.0
    container_name: manager
    ports:
      - "9082:9082"
    restart: unless-stopped
    volumes:
      - /tmp/manager_data:/ekuiper-manager/data
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081" 
    networks:
      - mynet
  
  ekuiper:
    image: lfedge/ekuiper:1.8.0
    ports:
      - "9081:9081"
    container_name: ekuiper
    hostname: ekuiper
    restart: unless-stopped
    user: root
    volumes:
      - /tmp/data:/kuiper/data
      - /tmp/log:/kuiper/log
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://broker.emqx.io:1883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
    networks:
      - mynet
  
  sensor-microservice:
    image: sensor-microservice
    container_name: sensor-microservice
    networks:
      - mynet
    depends_on:
      - postgres
      - mosquitto
  
networks:
  mynet:
    driver: bridge