// <auto-generated />
using System;
using DatabaseMaker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseMaker.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseMaker.Models.PondData", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntryId"));

                    b.Property<double>("Ammonia_g_mL")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DissolvedOxygen_g_mL")
                        .HasColumnType("double precision");

                    b.Property<double>("FishLength_cm")
                        .HasColumnType("double precision");

                    b.Property<double>("FishWeight_g")
                        .HasColumnType("double precision");

                    b.Property<double>("Nitrite_g_mL")
                        .HasColumnType("double precision");

                    b.Property<int>("PondId")
                        .HasColumnType("integer");

                    b.Property<double>("Population")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature_C")
                        .HasColumnType("double precision");

                    b.Property<double>("Turbidity_ntu")
                        .HasColumnType("double precision");

                    b.Property<double>("pH")
                        .HasColumnType("double precision");

                    b.HasKey("EntryId");

                    b.ToTable("PondData");
                });
#pragma warning restore 612, 618
        }
    }
}
